#!/bin/sh

if test x"$1" = x""; then
  dir=$(pwd)
else
  dir="$1"
fi

rm -f build_info.h
echo '/* autogenerated by make-build-info.sh */' > build_info.h
echo 'const char *REVISION = "'$(cd $dir && git rev-parse HEAD 2>/dev/null || echo "raw")'";' >> build_info.h
echo 'const char *BUILD_DATE = "'$(date +%Y%m%d-%H%M%S)'";' >> build_info.h
